import { Product } from "./types";
import { sampleProducts } from "./sample-data";

// All products combined from all pages — single source of truth
const additionalProducts: Product[] = [
  {
    id: 7,
    name: "Artisan Coffee Mug",
    creator: "Maria Garcia",
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.5,
    reviews: 98,
    image: "/api/placeholder/300/300",
    image2: "/api/placeholder/300/300",
    category: "Home Decor",
    description: "Beautiful handcrafted coffee mug perfect for your morning routine.",
    isNew: false,
    isLiked: false,
    inStock: true,
    store: "Craft Corner",
    tags: ["coffee", "mug", "handcrafted", "ceramic"],
  },
  {
    id: 8,
    name: "Premium Backpack",
    creator: "James Wilson",
    price: 149.99,
    originalPrice: null,
    rating: 4.7,
    reviews: 184,
    image: "/api/placeholder/300/300",
    image2: "/api/placeholder/300/300",
    category: "Accessories",
    description: "Durable backpack with multiple compartments and water-resistant material.",
    isNew: true,
    isLiked: false,
    inStock: true,
    store: "Travel Gear Pro",
    tags: ["backpack", "travel", "durable", "waterproof"],
  },
  {
    id: 9,
    name: "Silk Scarf Collection",
    creator: "Sophie Laurent",
    price: 89.99,
    originalPrice: 120.99,
    rating: 4.9,
    reviews: 76,
    image: "/api/placeholder/300/300",
    image2: "/api/placeholder/300/300",
    category: "Fashion",
    description: "Luxurious silk scarves with unique patterns and premium quality.",
    isNew: true,
    isLiked: true,
    inStock: true,
    store: "Luxury Silk Co.",
    tags: ["silk", "scarf", "luxury", "fashion"],
  },
  {
    id: 10,
    name: "Wooden Phone Stand",
    creator: "Tom Builder",
    price: 39.99,
    originalPrice: null,
    rating: 4.6,
    reviews: 134,
    image: "/api/placeholder/300/300",
    image2: "/api/placeholder/300/300",
    category: "Accessories",
    description: "Handcrafted wooden phone stand with adjustable angles.",
    isNew: false,
    isLiked: false,
    inStock: true,
    store: "Wood Works",
    tags: ["wood", "phone", "stand", "handcrafted"],
  },
  {
    id: 11,
    name: "Designer Sunglasses",
    creator: "Elena Fashions",
    price: 179.99,
    originalPrice: 229.99,
    rating: 4.8,
    reviews: 92,
    image: "/api/placeholder/300/300",
    image2: "/api/placeholder/300/300",
    category: "Accessories",
    description: "Premium designer sunglasses with UV protection and style.",
    isNew: false,
    isLiked: false,
    inStock: false,
    store: "Style Studio",
    tags: ["sunglasses", "designer", "uv-protection", "fashion"],
  },
  {
    id: 12,
    name: "Eco-Friendly Water Bottle",
    creator: "Green Life Co.",
    price: 29.99,
    originalPrice: null,
    rating: 4.4,
    reviews: 267,
    image: "/api/placeholder/300/300",
    image2: "/api/placeholder/300/300",
    category: "Accessories",
    description: "Sustainable water bottle made from recycled materials.",
    isNew: true,
    isLiked: true,
    inStock: true,
    store: "Eco Store",
    tags: ["eco-friendly", "water-bottle", "sustainable", "recycled"],
  },
];

export const allProducts: Product[] = [...sampleProducts, ...additionalProducts];
